//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMF.Transformations.Core {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMF.Transformations.Core.ErrorStrings", typeof(ErrorStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output of this computation has been delayed. Please subscribe to the OutputInitialized event to get informed when the Output has been created. If you were using the trace functionality, consider using the Trace methods to get the computation objects and wait until the output has been created. Alternatively, change the structure of your transformation rules to ensure that this computation has been initialized when you are making your request..
        /// </summary>
        internal static string ComputationOutputDelayed {
            get {
                return ResourceManager.GetString("ComputationOutputDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To instantiate a transformation rule, the current transformation rule must be an assignable of the specified transformation rule..
        /// </summary>
        internal static string MarkInstantiatingForMustInherit {
            get {
                return ResourceManager.GetString("MarkInstantiatingForMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule already instantiates another rule. Transformation rules must not instantiate multiple other transformation rules..
        /// </summary>
        internal static string MarkInstantiatingForOneRuleAtMost {
            get {
                return ResourceManager.GetString("MarkInstantiatingForOneRuleAtMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To require a transformation rule without specifying a selector, the current transformation rule must be assignable of the specified transformation rule..
        /// </summary>
        internal static string RequiresTransNoSelectorMustInherit {
            get {
                return ResourceManager.GetString("RequiresTransNoSelectorMustInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of created rules returned a null instance. This is not allowed. Please change the implementation to return a meaningful collection of transformation rules..
        /// </summary>
        internal static string TransformationCreateRulesNull {
            get {
                return ResourceManager.GetString("TransformationCreateRulesNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rules must be created and registered, before the transformation can be set initialized..
        /// </summary>
        internal static string TransformationSetIsInitializedNoRulesRegistered {
            get {
                return ResourceManager.GetString("TransformationSetIsInitializedNoRulesRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rules must be created, before they can be set initialized..
        /// </summary>
        internal static string TransformationSetIsRulesInitializedNoRulesCreated {
            get {
                return ResourceManager.GetString("TransformationSetIsRulesInitializedNoRulesCreated", resourceCulture);
            }
        }
    }
}
